// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hauls.sql

package database

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/lucas-ingemar/plock/pkg/types"
)

const addHaulCuisine = `-- name: AddHaulCuisine :exec
INSERT INTO haul_cuisines (haul_id, cuisine)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddHaulCuisineParams struct {
	HaulID  uuid.UUID     `json:"haul_id"`
	Cuisine types.Cuisine `json:"cuisine"`
}

func (q *Queries) AddHaulCuisine(ctx context.Context, arg AddHaulCuisineParams) error {
	_, err := q.db.ExecContext(ctx, addHaulCuisine, arg.HaulID, arg.Cuisine)
	return err
}

const addHaulProtein = `-- name: AddHaulProtein :exec
INSERT INTO haul_proteins (haul_id, protein)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddHaulProteinParams struct {
	HaulID  uuid.UUID     `json:"haul_id"`
	Protein types.Protein `json:"protein"`
}

func (q *Queries) AddHaulProtein(ctx context.Context, arg AddHaulProteinParams) error {
	_, err := q.db.ExecContext(ctx, addHaulProtein, arg.HaulID, arg.Protein)
	return err
}

const createHaul = `-- name: CreateHaul :one
INSERT INTO hauls (
    id,
    status,
    adults,
    children,
    servings_per_meal,
    meal_count,
    max_cooking_minutes
) VALUES (
    ?, "draft", ?, ?, ?, ?, ?
)
RETURNING id, status, adults, children, servings_per_meal, meal_count, max_cooking_minutes, created_at, updated_at
`

type CreateHaulParams struct {
	ID                uuid.UUID            `json:"id"`
	Adults            int64                `json:"adults"`
	Children          int64                `json:"children"`
	ServingsPerMeal   int64                `json:"servings_per_meal"`
	MealCount         int64                `json:"meal_count"`
	MaxCookingMinutes types.CookingMinutes `json:"max_cooking_minutes"`
}

func (q *Queries) CreateHaul(ctx context.Context, arg CreateHaulParams) (Haul, error) {
	row := q.db.QueryRowContext(ctx, createHaul,
		arg.ID,
		arg.Adults,
		arg.Children,
		arg.ServingsPerMeal,
		arg.MealCount,
		arg.MaxCookingMinutes,
	)
	var i Haul
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Adults,
		&i.Children,
		&i.ServingsPerMeal,
		&i.MealCount,
		&i.MaxCookingMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHaul = `-- name: GetHaul :one
SELECT id, status, adults, children, servings_per_meal, meal_count, max_cooking_minutes, created_at, updated_at FROM hauls
WHERE id = ? LIMIT 1
`

func (q *Queries) GetHaul(ctx context.Context, id uuid.UUID) (Haul, error) {
	row := q.db.QueryRowContext(ctx, getHaul, id)
	var i Haul
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Adults,
		&i.Children,
		&i.ServingsPerMeal,
		&i.MealCount,
		&i.MaxCookingMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHaulCuisines = `-- name: GetHaulCuisines :many
SELECT haul_id, cuisine FROM haul_cuisines
WHERE haul_id = ?
`

func (q *Queries) GetHaulCuisines(ctx context.Context, haulID uuid.UUID) ([]HaulCuisine, error) {
	rows, err := q.db.QueryContext(ctx, getHaulCuisines, haulID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HaulCuisine{}
	for rows.Next() {
		var i HaulCuisine
		if err := rows.Scan(&i.HaulID, &i.Cuisine); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHaulProteins = `-- name: GetHaulProteins :many
SELECT haul_id, protein FROM haul_proteins
WHERE haul_id = ?
`

func (q *Queries) GetHaulProteins(ctx context.Context, haulID uuid.UUID) ([]HaulProtein, error) {
	rows, err := q.db.QueryContext(ctx, getHaulProteins, haulID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HaulProtein{}
	for rows.Next() {
		var i HaulProtein
		if err := rows.Scan(&i.HaulID, &i.Protein); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHauls = `-- name: ListHauls :many
SELECT id, status, adults, children, servings_per_meal, meal_count, max_cooking_minutes, created_at, updated_at from hauls ORDER by created_at DESC
`

func (q *Queries) ListHauls(ctx context.Context) ([]Haul, error) {
	rows, err := q.db.QueryContext(ctx, listHauls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Haul{}
	for rows.Next() {
		var i Haul
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Adults,
			&i.Children,
			&i.ServingsPerMeal,
			&i.MealCount,
			&i.MaxCookingMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
