// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: haul_requests.sql

package database

import (
	"context"
)

const addHaulRequestCuisine = `-- name: AddHaulRequestCuisine :exec
INSERT INTO haul_request_cuisines (haul_request_id, cuisine)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddHaulRequestCuisineParams struct {
	HaulRequestID string `json:"haul_request_id"`
	Cuisine       string `json:"cuisine"`
}

func (q *Queries) AddHaulRequestCuisine(ctx context.Context, arg AddHaulRequestCuisineParams) error {
	_, err := q.db.ExecContext(ctx, addHaulRequestCuisine, arg.HaulRequestID, arg.Cuisine)
	return err
}

const addHaulRequestProtein = `-- name: AddHaulRequestProtein :exec
INSERT INTO haul_request_proteins (haul_request_id, protein)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddHaulRequestProteinParams struct {
	HaulRequestID string `json:"haul_request_id"`
	Protein       string `json:"protein"`
}

func (q *Queries) AddHaulRequestProtein(ctx context.Context, arg AddHaulRequestProteinParams) error {
	_, err := q.db.ExecContext(ctx, addHaulRequestProtein, arg.HaulRequestID, arg.Protein)
	return err
}

const createHaulRequest = `-- name: CreateHaulRequest :one
INSERT INTO haul_requests (
    id,
    adults,
    children,
    servings_per_meal,
    meal_count,
    max_cooking_minutes
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, adults, children, servings_per_meal, meal_count, max_cooking_minutes, created_at
`

type CreateHaulRequestParams struct {
	ID                string `json:"id"`
	Adults            int64  `json:"adults"`
	Children          int64  `json:"children"`
	ServingsPerMeal   int64  `json:"servings_per_meal"`
	MealCount         int64  `json:"meal_count"`
	MaxCookingMinutes int64  `json:"max_cooking_minutes"`
}

func (q *Queries) CreateHaulRequest(ctx context.Context, arg CreateHaulRequestParams) (HaulRequest, error) {
	row := q.db.QueryRowContext(ctx, createHaulRequest,
		arg.ID,
		arg.Adults,
		arg.Children,
		arg.ServingsPerMeal,
		arg.MealCount,
		arg.MaxCookingMinutes,
	)
	var i HaulRequest
	err := row.Scan(
		&i.ID,
		&i.Adults,
		&i.Children,
		&i.ServingsPerMeal,
		&i.MealCount,
		&i.MaxCookingMinutes,
		&i.CreatedAt,
	)
	return i, err
}
