// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type HaulRequest struct {
	ID                string    `json:"id"`
	Adults            int64     `json:"adults"`
	Children          int64     `json:"children"`
	ServingsPerMeal   int64     `json:"servings_per_meal"`
	MealCount         int64     `json:"meal_count"`
	MaxCookingMinutes int64     `json:"max_cooking_minutes"`
	CreatedAt         time.Time `json:"created_at"`
}

type HaulRequestCuisine struct {
	HaulRequestID string `json:"haul_request_id"`
	Cuisine       string `json:"cuisine"`
}

type HaulRequestProtein struct {
	HaulRequestID string `json:"haul_request_id"`
	Protein       string `json:"protein"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}
