// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	AddHaulRequestCuisine(ctx context.Context, arg AddHaulRequestCuisineParams) error
	AddHaulRequestProtein(ctx context.Context, arg AddHaulRequestProteinParams) error
	CreateHaulRequest(ctx context.Context, arg CreateHaulRequestParams) (HaulRequest, error)
}

var _ Querier = (*Queries)(nil)
