// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	AddHaulCuisine(ctx context.Context, arg AddHaulCuisineParams) error
	AddHaulProtein(ctx context.Context, arg AddHaulProteinParams) error
	CreateHaul(ctx context.Context, arg CreateHaulParams) (Haul, error)
}

var _ Querier = (*Queries)(nil)
