// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

type Querier interface {
	AddHaulCuisine(ctx context.Context, arg AddHaulCuisineParams) error
	AddHaulProtein(ctx context.Context, arg AddHaulProteinParams) error
	CreateHaul(ctx context.Context, arg CreateHaulParams) (Haul, error)
	GetHaul(ctx context.Context, id uuid.UUID) (Haul, error)
	GetHaulCuisines(ctx context.Context, haulID uuid.UUID) ([]HaulCuisine, error)
	GetHaulProteins(ctx context.Context, haulID uuid.UUID) ([]HaulProtein, error)
	ListHauls(ctx context.Context) ([]Haul, error)
}

var _ Querier = (*Queries)(nil)
