// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package database

import (
	"context"
	"database/sql"

	uuid "github.com/gofrs/uuid/v5"
)

const addReceipt = `-- name: AddReceipt :exec
INSERT INTO receipts (
    id,
    haul_id,
    currency,
    date,
    item_count,
    store,
    summary,
    total,
    total_savings
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddReceiptParams struct {
	ID           uuid.UUID       `json:"id"`
	HaulID       uuid.UUID       `json:"haul_id"`
	Currency     string          `json:"currency"`
	Date         string          `json:"date"`
	ItemCount    int64           `json:"item_count"`
	Store        string          `json:"store"`
	Summary      string          `json:"summary"`
	Total        float64         `json:"total"`
	TotalSavings sql.NullFloat64 `json:"total_savings"`
}

func (q *Queries) AddReceipt(ctx context.Context, arg AddReceiptParams) error {
	_, err := q.db.ExecContext(ctx, addReceipt,
		arg.ID,
		arg.HaulID,
		arg.Currency,
		arg.Date,
		arg.ItemCount,
		arg.Store,
		arg.Summary,
		arg.Total,
		arg.TotalSavings,
	)
	return err
}

const addReceiptItem = `-- name: AddReceiptItem :exec
INSERT INTO receipt_items (
    id,
    receipt_id,
    idx,
    brand,
    category,
    discount,
    is_food,
    name,
    price,
    quantity,
    unit
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddReceiptItemParams struct {
	ID        uuid.UUID       `json:"id"`
	ReceiptID uuid.UUID       `json:"receipt_id"`
	Idx       int64           `json:"idx"`
	Brand     sql.NullString  `json:"brand"`
	Category  sql.NullString  `json:"category"`
	Discount  sql.NullFloat64 `json:"discount"`
	IsFood    bool            `json:"is_food"`
	Name      string          `json:"name"`
	Price     float64         `json:"price"`
	Quantity  float64         `json:"quantity"`
	Unit      string          `json:"unit"`
}

func (q *Queries) AddReceiptItem(ctx context.Context, arg AddReceiptItemParams) error {
	_, err := q.db.ExecContext(ctx, addReceiptItem,
		arg.ID,
		arg.ReceiptID,
		arg.Idx,
		arg.Brand,
		arg.Category,
		arg.Discount,
		arg.IsFood,
		arg.Name,
		arg.Price,
		arg.Quantity,
		arg.Unit,
	)
	return err
}
