// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package database

import (
	"context"
	"database/sql"

	uuid "github.com/gofrs/uuid/v5"
)

const addRecipe = `-- name: AddRecipe :exec
INSERT INTO recipes (
    id,
    haul_id,
    haul_idx,
    cuisine,
    description,
    difficulty,
    kid_tips,
    protein,
    servings,
    title,
    total_time_minutes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddRecipeParams struct {
	ID               uuid.UUID      `json:"id"`
	HaulID           uuid.UUID      `json:"haul_id"`
	HaulIdx          int64          `json:"haul_idx"`
	Cuisine          string         `json:"cuisine"`
	Description      string         `json:"description"`
	Difficulty       string         `json:"difficulty"`
	KidTips          sql.NullString `json:"kid_tips"`
	Protein          string         `json:"protein"`
	Servings         int64          `json:"servings"`
	Title            string         `json:"title"`
	TotalTimeMinutes int64          `json:"total_time_minutes"`
}

func (q *Queries) AddRecipe(ctx context.Context, arg AddRecipeParams) error {
	_, err := q.db.ExecContext(ctx, addRecipe,
		arg.ID,
		arg.HaulID,
		arg.HaulIdx,
		arg.Cuisine,
		arg.Description,
		arg.Difficulty,
		arg.KidTips,
		arg.Protein,
		arg.Servings,
		arg.Title,
		arg.TotalTimeMinutes,
	)
	return err
}

const addRecipeIngredient = `-- name: AddRecipeIngredient :exec
INSERT INTO recipe_ingredients (
    id,
    recipe_id,
    idx,
    from_receipt,
    name,
    note,
    quantity,
    unit
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddRecipeIngredientParams struct {
	ID          uuid.UUID       `json:"id"`
	RecipeID    uuid.UUID       `json:"recipe_id"`
	Idx         int64           `json:"idx"`
	FromReceipt bool            `json:"from_receipt"`
	Name        string          `json:"name"`
	Note        sql.NullString  `json:"note"`
	Quantity    sql.NullFloat64 `json:"quantity"`
	Unit        sql.NullString  `json:"unit"`
}

func (q *Queries) AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeIngredient,
		arg.ID,
		arg.RecipeID,
		arg.Idx,
		arg.FromReceipt,
		arg.Name,
		arg.Note,
		arg.Quantity,
		arg.Unit,
	)
	return err
}

const addRecipeStep = `-- name: AddRecipeStep :exec
INSERT INTO recipe_steps (
    id,
    recipe_id,
    idx,
    text,
    timer_minutes
) VALUES (?, ?, ?, ?, ?)
`

type AddRecipeStepParams struct {
	ID           uuid.UUID     `json:"id"`
	RecipeID     uuid.UUID     `json:"recipe_id"`
	Idx          int64         `json:"idx"`
	Text         string        `json:"text"`
	TimerMinutes sql.NullInt64 `json:"timer_minutes"`
}

func (q *Queries) AddRecipeStep(ctx context.Context, arg AddRecipeStepParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeStep,
		arg.ID,
		arg.RecipeID,
		arg.Idx,
		arg.Text,
		arg.TimerMinutes,
	)
	return err
}
