// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package database

import (
	"context"
	"database/sql"

	uuid "github.com/gofrs/uuid/v5"
)

const addRecipe = `-- name: AddRecipe :exec
INSERT INTO recipes (
    id,
    haul_id,
    haul_idx,
    cuisine,
    description,
    difficulty,
    kid_tips,
    protein,
    servings,
    title,
    total_time_minutes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddRecipeParams struct {
	ID               uuid.UUID      `json:"id"`
	HaulID           uuid.UUID      `json:"haul_id"`
	HaulIdx          int64          `json:"haul_idx"`
	Cuisine          string         `json:"cuisine"`
	Description      string         `json:"description"`
	Difficulty       string         `json:"difficulty"`
	KidTips          sql.NullString `json:"kid_tips"`
	Protein          string         `json:"protein"`
	Servings         int64          `json:"servings"`
	Title            string         `json:"title"`
	TotalTimeMinutes int64          `json:"total_time_minutes"`
}

func (q *Queries) AddRecipe(ctx context.Context, arg AddRecipeParams) error {
	_, err := q.db.ExecContext(ctx, addRecipe,
		arg.ID,
		arg.HaulID,
		arg.HaulIdx,
		arg.Cuisine,
		arg.Description,
		arg.Difficulty,
		arg.KidTips,
		arg.Protein,
		arg.Servings,
		arg.Title,
		arg.TotalTimeMinutes,
	)
	return err
}

const addRecipeIngredient = `-- name: AddRecipeIngredient :exec
INSERT INTO recipe_ingredients (
    id,
    recipe_id,
    idx,
    from_receipt,
    name,
    note,
    quantity,
    unit
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddRecipeIngredientParams struct {
	ID          uuid.UUID       `json:"id"`
	RecipeID    uuid.UUID       `json:"recipe_id"`
	Idx         int64           `json:"idx"`
	FromReceipt bool            `json:"from_receipt"`
	Name        string          `json:"name"`
	Note        sql.NullString  `json:"note"`
	Quantity    sql.NullFloat64 `json:"quantity"`
	Unit        sql.NullString  `json:"unit"`
}

func (q *Queries) AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeIngredient,
		arg.ID,
		arg.RecipeID,
		arg.Idx,
		arg.FromReceipt,
		arg.Name,
		arg.Note,
		arg.Quantity,
		arg.Unit,
	)
	return err
}

const addRecipeStep = `-- name: AddRecipeStep :exec
INSERT INTO recipe_steps (
    id,
    recipe_id,
    idx,
    text,
    timer_minutes
) VALUES (?, ?, ?, ?, ?)
`

type AddRecipeStepParams struct {
	ID           uuid.UUID     `json:"id"`
	RecipeID     uuid.UUID     `json:"recipe_id"`
	Idx          int64         `json:"idx"`
	Text         string        `json:"text"`
	TimerMinutes sql.NullInt64 `json:"timer_minutes"`
}

func (q *Queries) AddRecipeStep(ctx context.Context, arg AddRecipeStepParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeStep,
		arg.ID,
		arg.RecipeID,
		arg.Idx,
		arg.Text,
		arg.TimerMinutes,
	)
	return err
}

const getRecipeSummaries = `-- name: GetRecipeSummaries :many
SELECT id, title from recipes WHERE haul_id = ? ORDER by haul_idx ASC
`

type GetRecipeSummariesRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) GetRecipeSummaries(ctx context.Context, haulID uuid.UUID) ([]GetRecipeSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeSummaries, haulID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecipeSummariesRow{}
	for rows.Next() {
		var i GetRecipeSummariesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredientsFromRecipeID = `-- name: ListRecipeIngredientsFromRecipeID :many
SELECT id, recipe_id, idx, from_receipt, name, note, quantity, unit, created_at, updated_at FROM recipe_ingredients WHERE recipe_id= ? ORDER BY idx ASC
`

func (q *Queries) ListRecipeIngredientsFromRecipeID(ctx context.Context, recipeID uuid.UUID) ([]RecipeIngredient, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeIngredientsFromRecipeID, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeIngredient{}
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Idx,
			&i.FromReceipt,
			&i.Name,
			&i.Note,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeStepsFromRecipeID = `-- name: ListRecipeStepsFromRecipeID :many
SELECT id, recipe_id, idx, text, timer_minutes, created_at, updated_at FROM recipe_steps WHERE recipe_id= ? ORDER BY idx ASC
`

func (q *Queries) ListRecipeStepsFromRecipeID(ctx context.Context, recipeID uuid.UUID) ([]RecipeStep, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeStepsFromRecipeID, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeStep{}
	for rows.Next() {
		var i RecipeStep
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Idx,
			&i.Text,
			&i.TimerMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesFromHaulID = `-- name: ListRecipesFromHaulID :many
SELECT id, haul_id, haul_idx, cuisine, description, difficulty, kid_tips, protein, servings, title, total_time_minutes, created_at, updated_at FROM recipes WHERE haul_id = ? ORDER BY haul_idx ASC
`

func (q *Queries) ListRecipesFromHaulID(ctx context.Context, haulID uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesFromHaulID, haulID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.HaulID,
			&i.HaulIdx,
			&i.Cuisine,
			&i.Description,
			&i.Difficulty,
			&i.KidTips,
			&i.Protein,
			&i.Servings,
			&i.Title,
			&i.TotalTimeMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
