// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type CookingMinutes int

var enumValues_CookingMinutes = []interface{}{
	20,
	30,
	45,
	60,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CookingMinutes) UnmarshalJSON(value []byte) error {
	var v int
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CookingMinutes {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CookingMinutes, v)
	}
	*j = CookingMinutes(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *CookingMinutes) UnmarshalYAML(value *yaml.Node) error {
	var v int
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CookingMinutes {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CookingMinutes, v)
	}
	*j = CookingMinutes(v)
	return nil
}
