// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Cuisine string

const CuisineAmerican Cuisine = "american"
const CuisineChinese Cuisine = "chinese"
const CuisineFrench Cuisine = "french"
const CuisineGreek Cuisine = "greek"
const CuisineIndian Cuisine = "indian"
const CuisineItalian Cuisine = "italian"
const CuisineJapanese Cuisine = "japanese"
const CuisineKorean Cuisine = "korean"
const CuisineLatinAmerican Cuisine = "latin_american"
const CuisineMexican Cuisine = "mexican"
const CuisineMoroccan Cuisine = "moroccan"
const CuisineSpanish Cuisine = "spanish"
const CuisineSwedish Cuisine = "swedish"
const CuisineThai Cuisine = "thai"
const CuisineTurkish Cuisine = "turkish"
const CuisineVietnamese Cuisine = "vietnamese"

var enumValues_Cuisine = []interface{}{
	"swedish",
	"italian",
	"french",
	"spanish",
	"greek",
	"turkish",
	"moroccan",
	"indian",
	"chinese",
	"thai",
	"japanese",
	"korean",
	"vietnamese",
	"mexican",
	"american",
	"latin_american",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Cuisine) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Cuisine {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Cuisine, v)
	}
	*j = Cuisine(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Cuisine) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Cuisine {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Cuisine, v)
	}
	*j = Cuisine(v)
	return nil
}
