// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// The AI assistant that generated the response, as reported by the assistant
// itself.
type GeneratedBy struct {
	// Assistant name, e.g. Claude or ChatGPT.
	Assistant string `json:"assistant"`

	// Model identifier as reported by the assistant.
	Model string `json:"model"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GeneratedBy) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["assistant"]; raw != nil && !ok {
		return fmt.Errorf("field assistant in GeneratedBy: required")
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in GeneratedBy: required")
	}
	type Plain GeneratedBy
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GeneratedBy(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *GeneratedBy) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["assistant"]; raw != nil && !ok {
		return fmt.Errorf("field assistant in GeneratedBy: required")
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in GeneratedBy: required")
	}
	type Plain GeneratedBy
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = GeneratedBy(plain)
	return nil
}
