// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// Receipt analysis and recipes returned by the AI assistant.
type HaulResponse struct {
	// The assistant that generated the response.
	GeneratedBy GeneratedBy `json:"generated_by"`

	// BCP 47 tag for all free text, e.g. sv-SE.
	Language string `json:"language"`

	// Analysis of the receipt.
	Receipt Receipt `json:"receipt"`

	// Generated recipes, one per planned meal.
	Recipes []GeneratedRecipe `json:"recipes"`

	// Short title for the whole set of recipes.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HaulResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["generated_by"]; raw != nil && !ok {
		return fmt.Errorf("field generated_by in HaulResponse: required")
	}
	if _, ok := raw["language"]; raw != nil && !ok {
		return fmt.Errorf("field language in HaulResponse: required")
	}
	if _, ok := raw["receipt"]; raw != nil && !ok {
		return fmt.Errorf("field receipt in HaulResponse: required")
	}
	if _, ok := raw["recipes"]; raw != nil && !ok {
		return fmt.Errorf("field recipes in HaulResponse: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in HaulResponse: required")
	}
	type Plain HaulResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Recipes != nil && len(plain.Recipes) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "recipes", 1)
	}
	*j = HaulResponse(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *HaulResponse) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["generated_by"]; raw != nil && !ok {
		return fmt.Errorf("field generated_by in HaulResponse: required")
	}
	if _, ok := raw["language"]; raw != nil && !ok {
		return fmt.Errorf("field language in HaulResponse: required")
	}
	if _, ok := raw["receipt"]; raw != nil && !ok {
		return fmt.Errorf("field receipt in HaulResponse: required")
	}
	if _, ok := raw["recipes"]; raw != nil && !ok {
		return fmt.Errorf("field recipes in HaulResponse: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in HaulResponse: required")
	}
	type Plain HaulResponse
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Recipes != nil && len(plain.Recipes) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "recipes", 1)
	}
	*j = HaulResponse(plain)
	return nil
}
