// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import "github.com/gofrs/uuid/v5"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "time"

// A grocery haul with the household and meal preferences used to plan it.
type Haul struct {
	// Number of adults in the household.
	Adults int `json:"adults"`

	// Number of children in the household.
	Children int `json:"children"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at"`

	// Preferred cuisines. An empty list means any cuisine.
	CuisinePreferences []Cuisine `json:"cuisine_preferences"`

	// UUID v4.
	ID uuid.UUID `json:"id"`

	// MaxCookingMinutes corresponds to the JSON schema field "max_cooking_minutes".
	MaxCookingMinutes CookingMinutes `json:"max_cooking_minutes"`

	// Number of meals to plan.
	MealCount int `json:"meal_count"`

	// Proteins the household eats. Proteins not listed are excluded from recipes.
	ProteinPreferences []Protein `json:"protein_preferences"`

	// Servings per meal, including any extra portions for leftovers.
	ServingsPerMeal int `json:"servings_per_meal"`

	// Status corresponds to the JSON schema field "status".
	Status Status `json:"status"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt time.Time `json:"updated_at"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Haul) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["adults"]; raw != nil && !ok {
		return fmt.Errorf("field adults in Haul: required")
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in Haul: required")
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in Haul: required")
	}
	if _, ok := raw["cuisine_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field cuisine_preferences in Haul: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Haul: required")
	}
	if _, ok := raw["max_cooking_minutes"]; raw != nil && !ok {
		return fmt.Errorf("field max_cooking_minutes in Haul: required")
	}
	if _, ok := raw["meal_count"]; raw != nil && !ok {
		return fmt.Errorf("field meal_count in Haul: required")
	}
	if _, ok := raw["protein_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field protein_preferences in Haul: required")
	}
	if _, ok := raw["servings_per_meal"]; raw != nil && !ok {
		return fmt.Errorf("field servings_per_meal in Haul: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in Haul: required")
	}
	if _, ok := raw["updated_at"]; raw != nil && !ok {
		return fmt.Errorf("field updated_at in Haul: required")
	}
	type Plain Haul
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 10 < plain.Adults {
		return fmt.Errorf("field %s: must be <= %v", "adults", 10)
	}
	if 1 > plain.Adults {
		return fmt.Errorf("field %s: must be >= %v", "adults", 1)
	}
	if 10 < plain.Children {
		return fmt.Errorf("field %s: must be <= %v", "children", 10)
	}
	if 0 > plain.Children {
		return fmt.Errorf("field %s: must be >= %v", "children", 0)
	}
	if 7 < plain.MealCount {
		return fmt.Errorf("field %s: must be <= %v", "meal_count", 7)
	}
	if 2 > plain.MealCount {
		return fmt.Errorf("field %s: must be >= %v", "meal_count", 2)
	}
	if plain.ProteinPreferences != nil && len(plain.ProteinPreferences) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "protein_preferences", 1)
	}
	if 8 < plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be <= %v", "servings_per_meal", 8)
	}
	if 1 > plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be >= %v", "servings_per_meal", 1)
	}
	*j = Haul(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Haul) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["adults"]; raw != nil && !ok {
		return fmt.Errorf("field adults in Haul: required")
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in Haul: required")
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in Haul: required")
	}
	if _, ok := raw["cuisine_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field cuisine_preferences in Haul: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Haul: required")
	}
	if _, ok := raw["max_cooking_minutes"]; raw != nil && !ok {
		return fmt.Errorf("field max_cooking_minutes in Haul: required")
	}
	if _, ok := raw["meal_count"]; raw != nil && !ok {
		return fmt.Errorf("field meal_count in Haul: required")
	}
	if _, ok := raw["protein_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field protein_preferences in Haul: required")
	}
	if _, ok := raw["servings_per_meal"]; raw != nil && !ok {
		return fmt.Errorf("field servings_per_meal in Haul: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in Haul: required")
	}
	if _, ok := raw["updated_at"]; raw != nil && !ok {
		return fmt.Errorf("field updated_at in Haul: required")
	}
	type Plain Haul
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if 10 < plain.Adults {
		return fmt.Errorf("field %s: must be <= %v", "adults", 10)
	}
	if 1 > plain.Adults {
		return fmt.Errorf("field %s: must be >= %v", "adults", 1)
	}
	if 10 < plain.Children {
		return fmt.Errorf("field %s: must be <= %v", "children", 10)
	}
	if 0 > plain.Children {
		return fmt.Errorf("field %s: must be >= %v", "children", 0)
	}
	if 7 < plain.MealCount {
		return fmt.Errorf("field %s: must be <= %v", "meal_count", 7)
	}
	if 2 > plain.MealCount {
		return fmt.Errorf("field %s: must be >= %v", "meal_count", 2)
	}
	if plain.ProteinPreferences != nil && len(plain.ProteinPreferences) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "protein_preferences", 1)
	}
	if 8 < plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be <= %v", "servings_per_meal", 8)
	}
	if 1 > plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be >= %v", "servings_per_meal", 1)
	}
	*j = Haul(plain)
	return nil
}

type Status string

const StatusArchived Status = "archived"
const StatusDraft Status = "draft"
const StatusFailed Status = "failed"
const StatusProcessing Status = "processing"
const StatusReady Status = "ready"

var enumValues_Status = []interface{}{
	"draft",
	"processing",
	"ready",
	"failed",
	"archived",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Status) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Status {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Status, v)
	}
	*j = Status(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Status) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Status {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Status, v)
	}
	*j = Status(v)
	return nil
}
