// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "unicode/utf8"

// A generated prompt the user can copy into their own AI assistant.
type HaulPrompt struct {
	// The full prompt text.
	Prompt string `json:"prompt"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HaulPrompt) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["prompt"]; raw != nil && !ok {
		return fmt.Errorf("field prompt in HaulPrompt: required")
	}
	type Plain HaulPrompt
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Prompt)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "prompt", 1)
	}
	*j = HaulPrompt(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *HaulPrompt) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["prompt"]; raw != nil && !ok {
		return fmt.Errorf("field prompt in HaulPrompt: required")
	}
	type Plain HaulPrompt
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Prompt)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "prompt", 1)
	}
	*j = HaulPrompt(plain)
	return nil
}
