// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import "github.com/gofrs/uuid/v5"
import yaml "gopkg.in/yaml.v3"
import "time"

// Fields shared by Haul and HaulSummary.
type HaulBase struct {
	// Number of adults in the household.
	Adults int `json:"adults"`

	// Number of children in the household.
	Children int `json:"children"`

	// When the haul was created.
	CreatedAt time.Time `json:"created_at"`

	// Preferred cuisines. An empty list means any cuisine.
	CuisinePreferences []Cuisine `json:"cuisine_preferences"`

	// The assistant that generated the recipes. Set once the AI response has been
	// added.
	GeneratedBy *GeneratedBy `json:"generated_by,omitempty,omitzero"`

	// UUID v4.
	ID uuid.UUID `json:"id"`

	// BCP 47 tag for all free text in the recipes, e.g. sv-SE. Set once the AI
	// response has been added.
	Language *string `json:"language,omitempty,omitzero"`

	// Maximum cooking time per meal.
	MaxCookingMinutes CookingMinutes `json:"max_cooking_minutes"`

	// Number of meals to plan.
	MealCount int `json:"meal_count"`

	// Proteins the household eats. Proteins not listed are excluded from recipes.
	ProteinPreferences []Protein `json:"protein_preferences"`

	// Servings per meal, including any extra portions for leftovers.
	ServingsPerMeal int `json:"servings_per_meal"`

	// Processing status of the haul.
	Status Status `json:"status"`

	// Short title for the whole set of recipes. Set once the AI response has been
	// added.
	Title *string `json:"title,omitempty,omitzero"`

	// When the haul was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HaulBase) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["adults"]; raw != nil && !ok {
		return fmt.Errorf("field adults in HaulBase: required")
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in HaulBase: required")
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in HaulBase: required")
	}
	if _, ok := raw["cuisine_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field cuisine_preferences in HaulBase: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in HaulBase: required")
	}
	if _, ok := raw["max_cooking_minutes"]; raw != nil && !ok {
		return fmt.Errorf("field max_cooking_minutes in HaulBase: required")
	}
	if _, ok := raw["meal_count"]; raw != nil && !ok {
		return fmt.Errorf("field meal_count in HaulBase: required")
	}
	if _, ok := raw["protein_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field protein_preferences in HaulBase: required")
	}
	if _, ok := raw["servings_per_meal"]; raw != nil && !ok {
		return fmt.Errorf("field servings_per_meal in HaulBase: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in HaulBase: required")
	}
	if _, ok := raw["updated_at"]; raw != nil && !ok {
		return fmt.Errorf("field updated_at in HaulBase: required")
	}
	type Plain HaulBase
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 10 < plain.Adults {
		return fmt.Errorf("field %s: must be <= %v", "adults", 10)
	}
	if 1 > plain.Adults {
		return fmt.Errorf("field %s: must be >= %v", "adults", 1)
	}
	if 10 < plain.Children {
		return fmt.Errorf("field %s: must be <= %v", "children", 10)
	}
	if 0 > plain.Children {
		return fmt.Errorf("field %s: must be >= %v", "children", 0)
	}
	if 7 < plain.MealCount {
		return fmt.Errorf("field %s: must be <= %v", "meal_count", 7)
	}
	if 2 > plain.MealCount {
		return fmt.Errorf("field %s: must be >= %v", "meal_count", 2)
	}
	if plain.ProteinPreferences != nil && len(plain.ProteinPreferences) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "protein_preferences", 1)
	}
	if 8 < plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be <= %v", "servings_per_meal", 8)
	}
	if 1 > plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be >= %v", "servings_per_meal", 1)
	}
	*j = HaulBase(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *HaulBase) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["adults"]; raw != nil && !ok {
		return fmt.Errorf("field adults in HaulBase: required")
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in HaulBase: required")
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in HaulBase: required")
	}
	if _, ok := raw["cuisine_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field cuisine_preferences in HaulBase: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in HaulBase: required")
	}
	if _, ok := raw["max_cooking_minutes"]; raw != nil && !ok {
		return fmt.Errorf("field max_cooking_minutes in HaulBase: required")
	}
	if _, ok := raw["meal_count"]; raw != nil && !ok {
		return fmt.Errorf("field meal_count in HaulBase: required")
	}
	if _, ok := raw["protein_preferences"]; raw != nil && !ok {
		return fmt.Errorf("field protein_preferences in HaulBase: required")
	}
	if _, ok := raw["servings_per_meal"]; raw != nil && !ok {
		return fmt.Errorf("field servings_per_meal in HaulBase: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in HaulBase: required")
	}
	if _, ok := raw["updated_at"]; raw != nil && !ok {
		return fmt.Errorf("field updated_at in HaulBase: required")
	}
	type Plain HaulBase
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if 10 < plain.Adults {
		return fmt.Errorf("field %s: must be <= %v", "adults", 10)
	}
	if 1 > plain.Adults {
		return fmt.Errorf("field %s: must be >= %v", "adults", 1)
	}
	if 10 < plain.Children {
		return fmt.Errorf("field %s: must be <= %v", "children", 10)
	}
	if 0 > plain.Children {
		return fmt.Errorf("field %s: must be >= %v", "children", 0)
	}
	if 7 < plain.MealCount {
		return fmt.Errorf("field %s: must be <= %v", "meal_count", 7)
	}
	if 2 > plain.MealCount {
		return fmt.Errorf("field %s: must be >= %v", "meal_count", 2)
	}
	if plain.ProteinPreferences != nil && len(plain.ProteinPreferences) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "protein_preferences", 1)
	}
	if 8 < plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be <= %v", "servings_per_meal", 8)
	}
	if 1 > plain.ServingsPerMeal {
		return fmt.Errorf("field %s: must be >= %v", "servings_per_meal", 1)
	}
	*j = HaulBase(plain)
	return nil
}
