// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// An ingredient in a recipe.
type Ingredient struct {
	// True if the ingredient comes from the receipt, false if it is a pantry staple.
	FromReceipt bool `json:"from_receipt"`

	// Ingredient name in the response language.
	Name string `json:"name"`

	// Preparation or usage note, e.g. 'drained'.
	Note *string `json:"note,omitempty,omitzero"`

	// Omitted for amounts like 'to taste'.
	Quantity *float64 `json:"quantity,omitempty,omitzero"`

	// Unit for quantity. Omitted for countless amounts like 'to taste'.
	Unit *Unit `json:"unit,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Ingredient) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from_receipt"]; raw != nil && !ok {
		return fmt.Errorf("field from_receipt in Ingredient: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Ingredient: required")
	}
	type Plain Ingredient
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Quantity != nil && 0 >= *plain.Quantity {
		return fmt.Errorf("field %s: must be > %v", "quantity", 0)
	}
	*j = Ingredient(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Ingredient) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["from_receipt"]; raw != nil && !ok {
		return fmt.Errorf("field from_receipt in Ingredient: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Ingredient: required")
	}
	type Plain Ingredient
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Quantity != nil && 0 >= *plain.Quantity {
		return fmt.Errorf("field %s: must be > %v", "quantity", 0)
	}
	*j = Ingredient(plain)
	return nil
}
