// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type ItemCategory string

const ItemCategoryBaby ItemCategory = "baby"
const ItemCategoryBeverages ItemCategory = "beverages"
const ItemCategoryBread ItemCategory = "bread"
const ItemCategoryDairy ItemCategory = "dairy"
const ItemCategoryFrozen ItemCategory = "frozen"
const ItemCategoryFruit ItemCategory = "fruit"
const ItemCategoryHousehold ItemCategory = "household"
const ItemCategoryHygiene ItemCategory = "hygiene"
const ItemCategoryOther ItemCategory = "other"
const ItemCategoryPantry ItemCategory = "pantry"
const ItemCategoryProtein ItemCategory = "protein"
const ItemCategoryReadyMeals ItemCategory = "ready_meals"
const ItemCategorySnacks ItemCategory = "snacks"
const ItemCategoryVegetables ItemCategory = "vegetables"

var enumValues_ItemCategory = []interface{}{
	"protein",
	"dairy",
	"vegetables",
	"fruit",
	"pantry",
	"bread",
	"frozen",
	"ready_meals",
	"baby",
	"snacks",
	"beverages",
	"household",
	"hygiene",
	"other",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ItemCategory) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ItemCategory {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ItemCategory, v)
	}
	*j = ItemCategory(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ItemCategory) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ItemCategory {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ItemCategory, v)
	}
	*j = ItemCategory(v)
	return nil
}
