// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Protein string

const ProteinBeef Protein = "beef"
const ProteinChicken Protein = "chicken"
const ProteinFish Protein = "fish"
const ProteinLamb Protein = "lamb"
const ProteinPork Protein = "pork"
const ProteinSeafood Protein = "seafood"
const ProteinVegan Protein = "vegan"
const ProteinVegetarian Protein = "vegetarian"

var enumValues_Protein = []interface{}{
	"chicken",
	"beef",
	"pork",
	"lamb",
	"fish",
	"seafood",
	"vegetarian",
	"vegan",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Protein) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Protein {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Protein, v)
	}
	*j = Protein(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Protein) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Protein {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Protein, v)
	}
	*j = Protein(v)
	return nil
}
