// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// One line on the receipt.
type ReceiptItem struct {
	// Brand name, when printed on the receipt.
	Brand *string `json:"brand,omitempty,omitzero"`

	// Item category.
	Category ItemCategory `json:"category"`

	// Discount as a positive number.
	Discount *float64 `json:"discount,omitempty,omitzero"`

	// False for non-food items like detergent or diapers.
	IsFood bool `json:"is_food"`

	// Normalized item name.
	Name string `json:"name"`

	// Line total before discount.
	Price float64 `json:"price"`

	// Total amount, e.g. 800 for two packs of 400 g.
	Quantity float64 `json:"quantity"`

	// Unit for quantity.
	Unit Unit `json:"unit"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReceiptItem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["category"]; raw != nil && !ok {
		return fmt.Errorf("field category in ReceiptItem: required")
	}
	if _, ok := raw["is_food"]; raw != nil && !ok {
		return fmt.Errorf("field is_food in ReceiptItem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ReceiptItem: required")
	}
	if _, ok := raw["price"]; raw != nil && !ok {
		return fmt.Errorf("field price in ReceiptItem: required")
	}
	if _, ok := raw["quantity"]; raw != nil && !ok {
		return fmt.Errorf("field quantity in ReceiptItem: required")
	}
	if _, ok := raw["unit"]; raw != nil && !ok {
		return fmt.Errorf("field unit in ReceiptItem: required")
	}
	type Plain ReceiptItem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Discount != nil && 0 > *plain.Discount {
		return fmt.Errorf("field %s: must be >= %v", "discount", 0)
	}
	if 0 > plain.Price {
		return fmt.Errorf("field %s: must be >= %v", "price", 0)
	}
	if 0 >= plain.Quantity {
		return fmt.Errorf("field %s: must be > %v", "quantity", 0)
	}
	*j = ReceiptItem(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ReceiptItem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["category"]; raw != nil && !ok {
		return fmt.Errorf("field category in ReceiptItem: required")
	}
	if _, ok := raw["is_food"]; raw != nil && !ok {
		return fmt.Errorf("field is_food in ReceiptItem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ReceiptItem: required")
	}
	if _, ok := raw["price"]; raw != nil && !ok {
		return fmt.Errorf("field price in ReceiptItem: required")
	}
	if _, ok := raw["quantity"]; raw != nil && !ok {
		return fmt.Errorf("field quantity in ReceiptItem: required")
	}
	if _, ok := raw["unit"]; raw != nil && !ok {
		return fmt.Errorf("field unit in ReceiptItem: required")
	}
	type Plain ReceiptItem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Discount != nil && 0 > *plain.Discount {
		return fmt.Errorf("field %s: must be >= %v", "discount", 0)
	}
	if 0 > plain.Price {
		return fmt.Errorf("field %s: must be >= %v", "price", 0)
	}
	if 0 >= plain.Quantity {
		return fmt.Errorf("field %s: must be > %v", "quantity", 0)
	}
	*j = ReceiptItem(plain)
	return nil
}
