// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import "github.com/atombender/go-jsonschema/pkg/types"
import yaml "gopkg.in/yaml.v3"
import "regexp"

// Analysis of the grocery receipt.
type Receipt struct {
	// ISO 4217 code, e.g. SEK.
	Currency string `json:"currency"`

	// Purchase date.
	Date types.SerializableDate `json:"date"`

	// Number of items according to the receipt.
	ItemCount int `json:"item_count"`

	// Every line on the receipt, including non-food items.
	Items []ReceiptItem `json:"items"`

	// Store or chain name, e.g. Willys.
	Store string `json:"store"`

	// One or two sentences describing the purchase.
	Summary string `json:"summary"`

	// Total amount paid, including fees.
	Total float64 `json:"total"`

	// Total discounts on the receipt, when printed.
	TotalSavings *float64 `json:"total_savings,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Receipt) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["currency"]; raw != nil && !ok {
		return fmt.Errorf("field currency in Receipt: required")
	}
	if _, ok := raw["date"]; raw != nil && !ok {
		return fmt.Errorf("field date in Receipt: required")
	}
	if _, ok := raw["item_count"]; raw != nil && !ok {
		return fmt.Errorf("field item_count in Receipt: required")
	}
	if _, ok := raw["items"]; raw != nil && !ok {
		return fmt.Errorf("field items in Receipt: required")
	}
	if _, ok := raw["store"]; raw != nil && !ok {
		return fmt.Errorf("field store in Receipt: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Receipt: required")
	}
	if _, ok := raw["total"]; raw != nil && !ok {
		return fmt.Errorf("field total in Receipt: required")
	}
	type Plain Receipt
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.Currency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Currency", `^[A-Z]{3}$`)
	}
	if 0 > plain.ItemCount {
		return fmt.Errorf("field %s: must be >= %v", "item_count", 0)
	}
	if 0 > plain.Total {
		return fmt.Errorf("field %s: must be >= %v", "total", 0)
	}
	if plain.TotalSavings != nil && 0 > *plain.TotalSavings {
		return fmt.Errorf("field %s: must be >= %v", "total_savings", 0)
	}
	*j = Receipt(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Receipt) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["currency"]; raw != nil && !ok {
		return fmt.Errorf("field currency in Receipt: required")
	}
	if _, ok := raw["date"]; raw != nil && !ok {
		return fmt.Errorf("field date in Receipt: required")
	}
	if _, ok := raw["item_count"]; raw != nil && !ok {
		return fmt.Errorf("field item_count in Receipt: required")
	}
	if _, ok := raw["items"]; raw != nil && !ok {
		return fmt.Errorf("field items in Receipt: required")
	}
	if _, ok := raw["store"]; raw != nil && !ok {
		return fmt.Errorf("field store in Receipt: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Receipt: required")
	}
	if _, ok := raw["total"]; raw != nil && !ok {
		return fmt.Errorf("field total in Receipt: required")
	}
	type Plain Receipt
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.Currency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Currency", `^[A-Z]{3}$`)
	}
	if 0 > plain.ItemCount {
		return fmt.Errorf("field %s: must be >= %v", "item_count", 0)
	}
	if 0 > plain.Total {
		return fmt.Errorf("field %s: must be >= %v", "total", 0)
	}
	if plain.TotalSavings != nil && 0 > *plain.TotalSavings {
		return fmt.Errorf("field %s: must be >= %v", "total_savings", 0)
	}
	*j = Receipt(plain)
	return nil
}
