// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import "github.com/gofrs/uuid/v5"
import yaml "gopkg.in/yaml.v3"

// A recipe generated from the receipt and household preferences.
type Recipe struct {
	// Cuisine the recipe belongs to.
	Cuisine Cuisine `json:"cuisine"`

	// One or two sentences describing the dish.
	Description string `json:"description"`

	// How demanding the recipe is to cook.
	Difficulty Difficulty `json:"difficulty"`

	// Recipe ID, UUID v4. Set by the server when the recipe is saved. Leave out when
	// generating recipes.
	ID *uuid.UUID `json:"id,omitempty,omitzero"`

	// Ingredients with amounts for the given servings.
	Ingredients []Ingredient `json:"ingredients"`

	// Adaptations for children in the household. Omitted when not relevant.
	KidTips *string `json:"kid_tips,omitempty,omitzero"`

	// Main protein in the recipe.
	Protein Protein `json:"protein"`

	// Number of servings the ingredient amounts are for.
	Servings int `json:"servings"`

	// Cooking steps in order.
	Steps []RecipeStep `json:"steps"`

	// Recipe name.
	Title string `json:"title"`

	// Total time from start to served, in minutes.
	TotalTimeMinutes int `json:"total_time_minutes"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Recipe) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cuisine"]; raw != nil && !ok {
		return fmt.Errorf("field cuisine in Recipe: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in Recipe: required")
	}
	if _, ok := raw["difficulty"]; raw != nil && !ok {
		return fmt.Errorf("field difficulty in Recipe: required")
	}
	if _, ok := raw["ingredients"]; raw != nil && !ok {
		return fmt.Errorf("field ingredients in Recipe: required")
	}
	if _, ok := raw["protein"]; raw != nil && !ok {
		return fmt.Errorf("field protein in Recipe: required")
	}
	if _, ok := raw["servings"]; raw != nil && !ok {
		return fmt.Errorf("field servings in Recipe: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in Recipe: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Recipe: required")
	}
	if _, ok := raw["total_time_minutes"]; raw != nil && !ok {
		return fmt.Errorf("field total_time_minutes in Recipe: required")
	}
	type Plain Recipe
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Ingredients != nil && len(plain.Ingredients) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "ingredients", 1)
	}
	if 1 > plain.Servings {
		return fmt.Errorf("field %s: must be >= %v", "servings", 1)
	}
	if plain.Steps != nil && len(plain.Steps) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "steps", 1)
	}
	if 1 > plain.TotalTimeMinutes {
		return fmt.Errorf("field %s: must be >= %v", "total_time_minutes", 1)
	}
	*j = Recipe(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Recipe) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["cuisine"]; raw != nil && !ok {
		return fmt.Errorf("field cuisine in Recipe: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in Recipe: required")
	}
	if _, ok := raw["difficulty"]; raw != nil && !ok {
		return fmt.Errorf("field difficulty in Recipe: required")
	}
	if _, ok := raw["ingredients"]; raw != nil && !ok {
		return fmt.Errorf("field ingredients in Recipe: required")
	}
	if _, ok := raw["protein"]; raw != nil && !ok {
		return fmt.Errorf("field protein in Recipe: required")
	}
	if _, ok := raw["servings"]; raw != nil && !ok {
		return fmt.Errorf("field servings in Recipe: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in Recipe: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Recipe: required")
	}
	if _, ok := raw["total_time_minutes"]; raw != nil && !ok {
		return fmt.Errorf("field total_time_minutes in Recipe: required")
	}
	type Plain Recipe
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Ingredients != nil && len(plain.Ingredients) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "ingredients", 1)
	}
	if 1 > plain.Servings {
		return fmt.Errorf("field %s: must be >= %v", "servings", 1)
	}
	if plain.Steps != nil && len(plain.Steps) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "steps", 1)
	}
	if 1 > plain.TotalTimeMinutes {
		return fmt.Errorf("field %s: must be >= %v", "total_time_minutes", 1)
	}
	*j = Recipe(plain)
	return nil
}
