// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import "github.com/gofrs/uuid/v5"
import yaml "gopkg.in/yaml.v3"

// Short version of a recipe, used in lists.
type RecipeSummary struct {
	// Recipe ID. UUID v4.
	ID uuid.UUID `json:"id"`

	// Recipe name.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipeSummary) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in RecipeSummary: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in RecipeSummary: required")
	}
	type Plain RecipeSummary
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RecipeSummary(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RecipeSummary) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in RecipeSummary: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in RecipeSummary: required")
	}
	type Plain RecipeSummary
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = RecipeSummary(plain)
	return nil
}
