// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// A household member's review of a recipe after cooking it.
type RecipeReview struct {
	// What the children thought. 1: didn't eat it, 2: so-so, 3: liked it. Omitted
	// when there are no children or no answer.
	ChildrenRating *int `json:"children_rating,omitempty,omitzero"`

	// Free-text note for next time, e.g. 'less salt'.
	Notes *string `json:"notes,omitempty,omitzero"`

	// Overall verdict. 1: not for us, 2: okay, 3: cook again.
	Rating int `json:"rating"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipeReview) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["rating"]; raw != nil && !ok {
		return fmt.Errorf("field rating in RecipeReview: required")
	}
	type Plain RecipeReview
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ChildrenRating != nil && 3 < *plain.ChildrenRating {
		return fmt.Errorf("field %s: must be <= %v", "children_rating", 3)
	}
	if plain.ChildrenRating != nil && 1 > *plain.ChildrenRating {
		return fmt.Errorf("field %s: must be >= %v", "children_rating", 1)
	}
	if 3 < plain.Rating {
		return fmt.Errorf("field %s: must be <= %v", "rating", 3)
	}
	if 1 > plain.Rating {
		return fmt.Errorf("field %s: must be >= %v", "rating", 1)
	}
	*j = RecipeReview(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RecipeReview) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["rating"]; raw != nil && !ok {
		return fmt.Errorf("field rating in RecipeReview: required")
	}
	type Plain RecipeReview
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.ChildrenRating != nil && 3 < *plain.ChildrenRating {
		return fmt.Errorf("field %s: must be <= %v", "children_rating", 3)
	}
	if plain.ChildrenRating != nil && 1 > *plain.ChildrenRating {
		return fmt.Errorf("field %s: must be >= %v", "children_rating", 1)
	}
	if 3 < plain.Rating {
		return fmt.Errorf("field %s: must be <= %v", "rating", 3)
	}
	if 1 > plain.Rating {
		return fmt.Errorf("field %s: must be >= %v", "rating", 1)
	}
	*j = RecipeReview(plain)
	return nil
}
