// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// One step in a recipe.
type RecipeStep struct {
	// Instruction for the step.
	Text string `json:"text"`

	// Set when the step involves waiting or cooking for a fixed time.
	TimerMinutes *int `json:"timer_minutes,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipeStep) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in RecipeStep: required")
	}
	type Plain RecipeStep
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.TimerMinutes != nil && 1 > *plain.TimerMinutes {
		return fmt.Errorf("field %s: must be >= %v", "timer_minutes", 1)
	}
	*j = RecipeStep(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RecipeStep) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in RecipeStep: required")
	}
	type Plain RecipeStep
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.TimerMinutes != nil && 1 > *plain.TimerMinutes {
		return fmt.Errorf("field %s: must be >= %v", "timer_minutes", 1)
	}
	*j = RecipeStep(plain)
	return nil
}
