// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Status string

const StatusArchived Status = "archived"
const StatusDraft Status = "draft"
const StatusFailed Status = "failed"
const StatusProcessing Status = "processing"
const StatusReady Status = "ready"

var enumValues_Status = []interface{}{
	"draft",
	"processing",
	"ready",
	"failed",
	"archived",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Status) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Status {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Status, v)
	}
	*j = Status(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Status) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Status {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Status, v)
	}
	*j = Status(v)
	return nil
}
