// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Unit string

const UnitCan Unit = "can"
const UnitClove Unit = "clove"
const UnitDl Unit = "dl"
const UnitG Unit = "g"
const UnitKg Unit = "kg"
const UnitL Unit = "l"
const UnitMl Unit = "ml"
const UnitPackage Unit = "package"
const UnitPiece Unit = "piece"
const UnitPinch Unit = "pinch"
const UnitTbsp Unit = "tbsp"
const UnitTsp Unit = "tsp"

var enumValues_Unit = []interface{}{
	"g",
	"kg",
	"ml",
	"dl",
	"l",
	"tsp",
	"tbsp",
	"pinch",
	"piece",
	"clove",
	"can",
	"package",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Unit) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Unit {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Unit, v)
	}
	*j = Unit(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Unit) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Unit {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Unit, v)
	}
	*j = Unit(v)
	return nil
}
